import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { Chip, Eyebrow, LUMA, PrimaryButton } from "@/components/luma-primitives";

const projectTypes = [
  { title: "Empty", detail: "Start from silence", icon: "⌁" },
  { title: "Beat", detail: "Start with drums", icon: "▦" },
  { title: "Band", detail: "Build a full song", icon: "⌁" },
  { title: "Podcast", detail: "Voice-first session", icon: "◉" },
];

export default function NewProjectScreen() {
  const router = useRouter();
  const [name, setName] = useState("New Track");
  const [tempo, setTempo] = useState("124");
  const [selectedType, setSelectedType] = useState("Empty");
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><View style={styles.root}><View style={styles.topbar}><Pressable onPress={() => router.back()}><Text style={styles.close}>×</Text></Pressable><Text style={styles.topTitle}>New Project</Text><Pressable onPress={() => router.replace("/studio")}><Text style={styles.close}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow>PROJECT SETUP</Eyebrow><Text style={styles.heading}>Start with a clear idea.</Text><Text style={styles.subheading}>Set the basics now. Everything stays editable inside the studio.</Text><View style={styles.field}><Text style={styles.label}>PROJECT NAME</Text><TextInput value={name} onChangeText={setName} placeholder="New Track" placeholderTextColor={LUMA.muted} style={styles.input} /></View><View style={styles.field}><Text style={styles.label}>TEMPO (BPM)</Text><View style={styles.stepper}><TextInput value={tempo} onChangeText={setTempo} keyboardType="number-pad" style={styles.tempoInput} /><Pressable onPress={() => setTempo(String(Math.max(40, Number(tempo || 0) - 1)))} style={styles.stepperButton}><Text style={styles.stepText}>−</Text></Pressable><Pressable onPress={() => setTempo(String(Math.min(220, Number(tempo || 0) + 1)))} style={styles.stepperButton}><Text style={styles.stepText}>＋</Text></Pressable></View></View><View style={styles.field}><Text style={styles.label}>TIME SIGNATURE</Text><Chip active>4 / 4⌄</Chip></View><View style={styles.field}><Text style={styles.label}>KEY</Text><Chip active>C Major⌄</Chip></View><View style={styles.field}><Text style={styles.label}>LENGTH</Text><Chip active>4:00⌄</Chip></View><View style={styles.field}><Text style={styles.label}>PROJECT TYPE</Text><View style={styles.typeGrid}>{projectTypes.map((type) => <Pressable key={type.title} onPress={() => setSelectedType(type.title)} style={[styles.typeCard, selectedType === type.title && styles.typeCardActive]}><Text style={[styles.typeIcon, selectedType === type.title && { color: LUMA.violet }]}>{type.icon}</Text><Text style={styles.typeTitle}>{type.title}</Text><Text style={styles.typeDetail}>{type.detail}</Text></Pressable>)}</View></View><View style={styles.importRow}><Text style={styles.importIcon}>↥</Text><View style={styles.importBody}><Text style={styles.importTitle}>Import files</Text><Text style={styles.importDetail}>Audio, MIDI, or project files</Text></View><Text style={styles.arrow}>›</Text></View><PrimaryButton onPress={() => router.replace("/studio")}>Create project</PrimaryButton></ScrollView></View></ScreenContainer>;
}

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: LUMA.canvas }, topbar: { height: 60, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 18, borderBottomWidth: 1, borderBottomColor: LUMA.border }, topTitle: { color: LUMA.text, fontSize: 13, fontWeight: "900" }, close: { color: LUMA.text, fontSize: 26 }, content: { padding: 20, paddingBottom: 42, gap: 17 }, heading: { color: LUMA.text, fontSize: 29, fontWeight: "900", letterSpacing: -0.8, marginTop: 6 }, subheading: { color: LUMA.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, field: { gap: 8 }, label: { color: LUMA.muted, fontSize: 8, fontWeight: "900", letterSpacing: 1 }, input: { color: LUMA.text, fontSize: 14, fontWeight: "800", backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12 }, stepper: { flexDirection: "row", alignItems: "center", gap: 8 }, tempoInput: { flex: 1, color: LUMA.text, fontSize: 14, fontWeight: "800", backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12 }, stepperButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center", backgroundColor: LUMA.raised, borderWidth: 1, borderColor: LUMA.border, borderRadius: 10 }, stepText: { color: LUMA.text, fontSize: 18 }, typeGrid: { flexDirection: "row", gap: 8 }, typeCard: { flex: 1, minHeight: 82, padding: 9, borderRadius: 10, borderWidth: 1, borderColor: LUMA.border, backgroundColor: LUMA.surface }, typeCardActive: { borderColor: LUMA.violet, backgroundColor: "#1C1237" }, typeIcon: { color: LUMA.muted, fontSize: 18 }, typeTitle: { color: LUMA.text, fontSize: 10, fontWeight: "900", marginTop: 6 }, typeDetail: { color: LUMA.muted, fontSize: 7, marginTop: 3 }, importRow: { flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderWidth: 1, borderColor: LUMA.border, borderRadius: 10, backgroundColor: LUMA.surface }, importIcon: { color: LUMA.cyan, fontSize: 21 }, importBody: { flex: 1 }, importTitle: { color: LUMA.text, fontSize: 11, fontWeight: "900" }, importDetail: { color: LUMA.muted, fontSize: 9, marginTop: 3 }, arrow: { color: LUMA.muted, fontSize: 22 },
});
