import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { Chip, Eyebrow, LUMA, PrimaryButton } from "@/components/luma-primitives";

const projectTypes = [
  { title: "Song", detail: "Record + arrange", icon: "○" },
  { title: "Beat", detail: "Start with drums", icon: "▦" },
  { title: "MIDI", detail: "Start with keys", icon: "⌁" },
  { title: "Voice", detail: "Capture a take", icon: "◉" },
];

export default function NewProjectScreen() {
  const router = useRouter();
  const [name, setName] = useState("New Session");
  const [tempo, setTempo] = useState("124");
  const [selectedType, setSelectedType] = useState("Song");
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#070A12]" safeAreaClassName="bg-[#070A12]"><View style={styles.root}><View style={styles.topbar}><Pressable onPress={() => router.back()} style={styles.topButton}><Text style={styles.close}>‹</Text></Pressable><Text style={styles.topTitle}>New session</Text><Pressable onPress={() => router.back()} style={styles.topButton}><Text style={styles.done}>Cancel</Text></Pressable></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Eyebrow>SESSION SETUP</Eyebrow><Text style={styles.heading}>Start a session.</Text><Text style={styles.subheading}>Choose the first thing you want to work on. You can add tracks later.</Text><View style={styles.field}><Text style={styles.label}>NAME</Text><TextInput value={name} onChangeText={setName} placeholder="New Session" placeholderTextColor={LUMA.muted} style={styles.input} /></View><View style={styles.inlineFields}><View style={styles.tempoField}><Text style={styles.label}>TEMPO</Text><View style={styles.stepper}><TextInput value={tempo} onChangeText={setTempo} keyboardType="number-pad" style={styles.tempoInput} /><Pressable onPress={() => setTempo(String(Math.max(40, Number(tempo || 0) - 1)))} style={styles.stepperButton}><Text style={styles.stepText}>−</Text></Pressable><Pressable onPress={() => setTempo(String(Math.min(220, Number(tempo || 0) + 1)))} style={styles.stepperButton}><Text style={styles.stepText}>＋</Text></Pressable></View></View><View style={styles.smallField}><Text style={styles.label}>KEY</Text><Chip active>C major⌄</Chip></View></View><View style={styles.field}><Text style={styles.label}>STARTING POINT</Text><View style={styles.typeGrid}>{projectTypes.map((type) => <Pressable key={type.title} onPress={() => setSelectedType(type.title)} style={({ pressed }) => [styles.typeCard, selectedType === type.title && styles.typeCardActive, pressed && styles.pressed]}><Text style={[styles.typeIcon, selectedType === type.title && { color: LUMA.cyan }]}>{type.icon}</Text><Text style={styles.typeTitle}>{type.title}</Text><Text style={styles.typeDetail}>{type.detail}</Text></Pressable>)}</View></View><View style={styles.settingsLine}><Text style={styles.label}>TIME SIGNATURE</Text><Text style={styles.value}>4 / 4⌄</Text></View><View style={styles.settingsLine}><Text style={styles.label}>LENGTH</Text><Text style={styles.value}>4:00⌄</Text></View><Pressable style={({ pressed }) => [styles.importRow, pressed && styles.pressed]}><Text style={styles.importIcon}>↥</Text><View style={styles.importBody}><Text style={styles.importTitle}>Bring in an instrumental</Text><Text style={styles.importDetail}>MP3, WAV, or M4A</Text></View><Text style={styles.arrow}>›</Text></Pressable><PrimaryButton onPress={() => router.replace("/studio")}>Open session</PrimaryButton></ScrollView></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: LUMA.canvas }, topbar: { height: 56, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: LUMA.hairline }, topButton: { minWidth: 48 }, topTitle: { color: LUMA.text, fontSize: 13, fontWeight: "800" }, close: { color: LUMA.text, fontSize: 27, lineHeight: 27 }, done: { color: LUMA.cyan, fontSize: 11, fontWeight: "800", textAlign: "right" }, content: { padding: 18, paddingBottom: 42, gap: 17 }, heading: { color: LUMA.text, fontSize: 30, fontWeight: "800", letterSpacing: -1, marginTop: 6 }, subheading: { color: LUMA.muted, fontSize: 12, lineHeight: 18, marginTop: 5, maxWidth: 340 }, field: { gap: 8 }, label: { color: LUMA.muted, fontSize: 8, fontWeight: "800", letterSpacing: 1.1 }, input: { color: LUMA.text, fontSize: 15, fontWeight: "800", backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 7, paddingHorizontal: 11, paddingVertical: 11 }, inlineFields: { flexDirection: "row", gap: 12 }, tempoField: { flex: 1, gap: 8 }, smallField: { width: 110, gap: 8 }, stepper: { flexDirection: "row", alignItems: "center", gap: 6 }, tempoInput: { flex: 1, color: LUMA.text, fontSize: 14, fontWeight: "800", backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 7, paddingHorizontal: 10, paddingVertical: 10 }, stepperButton: { width: 34, height: 38, alignItems: "center", justifyContent: "center", backgroundColor: LUMA.raised, borderWidth: 1, borderColor: LUMA.border, borderRadius: 6 }, stepText: { color: LUMA.text, fontSize: 17 }, typeGrid: { flexDirection: "row", gap: 7 }, typeCard: { flex: 1, minHeight: 78, padding: 9, borderRadius: 7, borderWidth: 1, borderColor: LUMA.border, backgroundColor: LUMA.surface }, typeCardActive: { borderColor: LUMA.cyan, backgroundColor: "#0D2631" }, typeIcon: { color: LUMA.muted, fontSize: 18 }, typeTitle: { color: LUMA.text, fontSize: 11, fontWeight: "800", marginTop: 6 }, typeDetail: { color: LUMA.muted, fontSize: 8, marginTop: 3 }, settingsLine: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: LUMA.hairline, paddingVertical: 13 }, value: { color: LUMA.text, fontSize: 11, fontWeight: "800" }, importRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 13, borderTopWidth: 1, borderBottomWidth: 1, borderColor: LUMA.hairline }, importIcon: { color: LUMA.cyan, fontSize: 21 }, importBody: { flex: 1 }, importTitle: { color: LUMA.text, fontSize: 11, fontWeight: "800" }, importDetail: { color: LUMA.muted, fontSize: 9, marginTop: 3 }, arrow: { color: LUMA.muted, fontSize: 22 }, pressed: { opacity: 0.68 },
});
