import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, Eyebrow, LUMA, PrimaryButton } from "@/components/luma-primitives";

export default function AiTab() {
  const router = useRouter();
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Eyebrow>AI CO-PRODUCER</Eyebrow><Text style={styles.title}>Create without limits.</Text><Text style={styles.copy}>Luma helps you move from a blank project to an editable musical idea.</Text><View style={styles.orb}><Text style={styles.orbText}>✦</Text></View></View><Text style={styles.question}>What would you like to work on?</Text>{["Generate a beat from this groove", "Suggest chords for my chorus", "Make the vocal feel more present", "Analyze my mix"].map((item, index) => <Pressable key={item} onPress={() => router.push("/editor/ai")} style={({ pressed }) => [styles.option, pressed && styles.pressed]}><View style={styles.optionIcon}><Text style={{ color: index === 0 ? LUMA.violet : LUMA.cyan }}>✦</Text></View><View style={styles.optionBody}><Text style={styles.optionTitle}>{item}</Text><Text style={styles.optionMeta}>Editable and reversible</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}<PrimaryButton onPress={() => router.push("/editor/ai")}>Open AI co-producer</PrimaryButton><Card><Eyebrow>YOUR CONTROL</Eyebrow><Text style={styles.cardTitle}>Nothing changes without your approval.</Text><Text style={styles.cardCopy}>Luma suggestions are previews. You can listen, edit, apply, or undo every idea.</Text></Card></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 40, gap: 14 }, hero: { minHeight: 190, padding: 18, borderRadius: 20, borderWidth: 1, borderColor: "#49327A", backgroundColor: "#0C1022", overflow: "hidden" }, title: { color: LUMA.text, fontSize: 29, fontWeight: "900", marginTop: 7 }, copy: { color: LUMA.muted, fontSize: 12, lineHeight: 18, maxWidth: 265, marginTop: 6 }, orb: { position: "absolute", right: 18, bottom: 15, width: 92, height: 92, borderRadius: 46, backgroundColor: "#241244", alignItems: "center", justifyContent: "center" }, orbText: { color: LUMA.violet, fontSize: 42 }, question: { color: LUMA.text, fontSize: 15, fontWeight: "900" }, option: { flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 13, borderWidth: 1, borderColor: LUMA.border, backgroundColor: LUMA.surface }, optionIcon: { width: 31, height: 31, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: LUMA.raised }, optionBody: { flex: 1 }, optionTitle: { color: LUMA.text, fontSize: 11, fontWeight: "900" }, optionMeta: { color: LUMA.muted, fontSize: 9, marginTop: 3 }, arrow: { color: LUMA.cyan, fontSize: 22 }, pressed: { opacity: 0.76, transform: [{ scale: 0.98 }] }, cardTitle: { color: LUMA.text, fontSize: 16, fontWeight: "900", marginTop: 6 }, cardCopy: { color: LUMA.muted, fontSize: 11, lineHeight: 16, marginTop: 6 },
});
