import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Chip, Eyebrow, LUMA, PrimaryButton } from "@/components/luma-primitives";
import { MotionCard } from "@/components/motion";

const projects = [
  { title: "Midnight Drive", meta: "124 BPM · 4m ago", color: LUMA.violet, kind: "beat" },
  { title: "Neon Skyline", meta: "128 BPM · 7h ago", color: LUMA.cyan, kind: "record" },
  { title: "Velvet Dreams", meta: "92 BPM · 2d ago", color: LUMA.amber, kind: "midi" },
  { title: "Ocean Echoes", meta: "105 BPM · 3d ago", color: "#5A8DEE", kind: "loop" },
  { title: "High Voltage", meta: "140 BPM · 5d ago", color: "#EF6C9B", kind: "beat" },
  { title: "Lo-Fi Sunrise", meta: "78 BPM · 1w ago", color: "#E88A45", kind: "record" },
];

export default function ProjectsScreen() {
  const router = useRouter();
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.brand}>LUMA AUDIO</Text><Text style={styles.title}>Projects</Text></View><Pressable onPress={() => router.push("/project/new")} style={styles.newButton}><Text style={styles.plus}>＋</Text><Text style={styles.newText}>New Project</Text></Pressable></View><View style={styles.filters}><Chip active>All</Chip><Chip>Local</Chip><Chip>Cloud</Chip><Chip>Starred</Chip></View><View style={styles.projectList}>{projects.map((project) => <MotionCard key={project.title} onPress={() => router.push("/studio")} style={styles.projectCard}><View style={[styles.art, { backgroundColor: project.color }]}><View style={styles.artWave}>{Array.from({ length: 6 }, (_, index) => <View key={index} style={[styles.artBar, { height: `${30 + ((index * 23) % 58)}%` }]} />)}</View></View><View style={styles.projectBody}><Text style={styles.projectTitle}>{project.title}</Text><Text style={styles.projectMeta}>{project.meta}</Text><View style={styles.projectFoot}><Text style={styles.kind}>{project.kind.toUpperCase()}</Text><Text style={styles.star}>☆</Text></View></View><Text style={styles.more}>•••</Text></MotionCard>)}</View><View style={styles.footerCard}><Eyebrow>WORKSPACE</Eyebrow><Text style={styles.footerTitle}>One timeline. Every idea.</Text><Text style={styles.footerCopy}>Record vocals, upload an instrumental, make beats, and keep the whole song in one Luma project.</Text><PrimaryButton onPress={() => router.push("/project/new")}>Create a project</PrimaryButton></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ scroll: { flex: 1, backgroundColor: LUMA.canvas }, content: { padding: 18, paddingBottom: 40, gap: 15 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, brand: { color: LUMA.cyan, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: LUMA.text, fontSize: 30, fontWeight: "900", letterSpacing: -0.9, marginTop: 6 }, newButton: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: LUMA.violet, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9 }, plus: { color: LUMA.text, fontSize: 15 }, newText: { color: LUMA.text, fontSize: 10, fontWeight: "900" }, filters: { flexDirection: "row", gap: 8 }, projectList: { gap: 9 }, projectCard: { flexDirection: "row", alignItems: "center", gap: 11, padding: 9, minHeight: 70, borderRadius: 14, backgroundColor: LUMA.surface }, art: { width: 54, height: 54, borderRadius: 9, alignItems: "center", justifyContent: "center", overflow: "hidden" }, artWave: { flexDirection: "row", alignItems: "center", gap: 2, height: 34 }, artBar: { width: 3, backgroundColor: "rgba(255,255,255,0.84)", borderRadius: 2 }, projectBody: { flex: 1 }, projectTitle: { color: LUMA.text, fontSize: 13, fontWeight: "900" }, projectMeta: { color: LUMA.muted, fontSize: 9, marginTop: 4 }, projectFoot: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 5 }, kind: { color: LUMA.cyan, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 }, star: { color: LUMA.amber, fontSize: 17 }, more: { color: LUMA.muted, fontSize: 16, paddingHorizontal: 3 }, footerCard: { padding: 16, borderRadius: 17, borderWidth: 1, borderColor: LUMA.border, backgroundColor: "#0A1121", gap: 8 }, footerTitle: { color: LUMA.text, fontSize: 17, fontWeight: "900", marginTop: 4 }, footerCopy: { color: LUMA.muted, fontSize: 10, lineHeight: 15, marginBottom: 5 },
});
