import { ScrollView, StyleSheet, Text, View, Pressable } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, Chip, Eyebrow, LUMA, PrimaryButton, SectionTitle } from "@/components/luma-primitives";
import { MotionCard } from "@/components/motion";

const projects = [
  { title: "Midnight Bloom", meta: "118 BPM · F minor · 8 tracks", color: LUMA.violet, age: "Saved 2 min ago" },
  { title: "Neon Rooms", meta: "102 BPM · C minor · 4 tracks", color: LUMA.cyan, age: "Saved yesterday" },
  { title: "Untitled idea", meta: "96 BPM · A minor · 1 take", color: LUMA.amber, age: "Saved 3 days ago" },
];

export default function HomeScreen() {
  const router = useRouter();
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.topbar}><View><Text style={styles.brand}>LUMA AUDIO</Text><Text style={styles.title}>Make something real.</Text><Text style={styles.subtitle}>A focused studio for ideas that deserve a finished song.</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>L</Text></View></View>
    <Card style={styles.hero}><View style={styles.heroGlow} /><Eyebrow>CONTINUE CREATING</Eyebrow><Text style={styles.heroTitle}>Midnight Bloom</Text><Text style={styles.heroMeta}>118 BPM · F minor · Last opened 2 min ago</Text><View style={styles.heroWave}>{Array.from({ length: 34 }, (_, index) => <View key={index} style={[styles.wave, { height: `${30 + ((index * 17) % 65)}%` }]} />)}</View><PrimaryButton onPress={() => router.push("/studio")}>Open studio</PrimaryButton></Card>
    <View style={styles.sectionRow}><SectionTitle eyebrow="PROJECTS" title="Your sessions" detail={`${projects.length} saved`} /><Pressable onPress={() => router.push("/project/new")}><Text style={styles.link}>See all</Text></Pressable></View>
    <View style={styles.filterRow}><Chip active>Recent</Chip><Chip>Shared</Chip><Chip>Drafts</Chip></View>
    {projects.map((project) => <MotionCard key={project.title} onPress={() => router.push("/studio")} style={{ ...styles.projectCard, borderColor: project.color + "55" }}><View style={[styles.projectMark, { backgroundColor: project.color }]} /><View style={styles.projectBody}><Text style={styles.projectTitle}>{project.title}</Text><Text style={styles.projectMeta}>{project.meta}</Text><Text style={styles.projectAge}>{project.age}</Text></View><Text style={styles.chevron}>›</Text></MotionCard>)}
    <View style={styles.sectionRow}><SectionTitle eyebrow="START FRESH" title="Choose a starting point" /></View>
    <View style={styles.startGrid}><StartCard label="Record" detail="Capture a take" icon="●" color={LUMA.violet} onPress={() => router.push("/project/new")} /><StartCard label="Beat" detail="Build a rhythm" icon="▦" color={LUMA.cyan} onPress={() => router.push("/project/new")} /><StartCard label="Loop" detail="Browse sounds" icon="≋" color={LUMA.amber} onPress={() => router.push("/library")} /></View>
    <Card><SectionTitle eyebrow="FOCUSED EDITORS" title="Go deeper when you need it" /><View style={styles.editorRow}><Chip onPress={() => router.push("/editor/beat")}>Beat</Chip><Chip onPress={() => router.push("/editor/midi")}>MIDI</Chip><Chip onPress={() => router.push("/editor/mix")}>Mix</Chip><Chip onPress={() => router.push("/editor/ai")}>AI</Chip><Chip onPress={() => router.push("/editor/export")}>Export</Chip></View></Card>
  </ScrollView></ScreenContainer>;
}

function StartCard({ label, detail, icon, color, onPress }: { label: string; detail: string; icon: string; color: string; onPress: () => void }) { return <MotionCard onPress={onPress} style={styles.startCard}><Text style={[styles.startIcon, { color }]}>{icon}</Text><Text style={styles.startLabel}>{label}</Text><Text style={styles.startDetail}>{detail}</Text></MotionCard>; }

const styles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: LUMA.canvas }, content: { padding: 18, paddingBottom: 42, gap: 14 }, topbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, brand: { color: LUMA.cyan, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { color: LUMA.text, fontSize: 30, fontWeight: "900", letterSpacing: -1, marginTop: 7 }, subtitle: { color: LUMA.muted, fontSize: 12, lineHeight: 17, maxWidth: 290, marginTop: 6 }, avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#2A1452", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#7138B5" }, avatarText: { color: LUMA.text, fontWeight: "900" }, hero: { overflow: "hidden", marginTop: 6 }, heroGlow: { position: "absolute", top: -80, right: -40, width: 220, height: 180, borderRadius: 180, backgroundColor: "#2A1452", opacity: 0.55 }, heroTitle: { color: LUMA.text, fontSize: 25, fontWeight: "900", marginTop: 7 }, heroMeta: { color: LUMA.muted, fontSize: 11, marginTop: 4 }, heroWave: { height: 52, flexDirection: "row", alignItems: "center", gap: 3, marginVertical: 16 }, wave: { flex: 1, backgroundColor: LUMA.cyan, opacity: 0.8, borderRadius: 3 }, sectionRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginTop: 6 }, link: { color: LUMA.cyan, fontSize: 10, fontWeight: "900", marginBottom: 3 }, filterRow: { flexDirection: "row", gap: 8 }, projectCard: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 13 }, projectMark: { width: 8, height: 44, borderRadius: 6 }, projectBody: { flex: 1 }, projectTitle: { color: LUMA.text, fontSize: 14, fontWeight: "900" }, projectMeta: { color: LUMA.muted, fontSize: 10, marginTop: 4 }, projectAge: { color: "#5F6E8A", fontSize: 9, marginTop: 6 }, chevron: { color: LUMA.muted, fontSize: 24 },   startGrid: { flexDirection: "row", gap: 9 }, editorRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 }, startCard: { flex: 1, backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 15, padding: 12, minHeight: 94 }, startIcon: { fontSize: 21, fontWeight: "900" }, startLabel: { color: LUMA.text, fontSize: 12, fontWeight: "900", marginTop: 12 }, startDetail: { color: LUMA.muted, fontSize: 9, marginTop: 4 },
});
