import { ScrollView, StyleSheet, Text, View, Pressable } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, Chip, Eyebrow, LUMA, SectionTitle } from "@/components/luma-primitives";

const sounds = [
  { name: "Glass Horizon", type: "Synth loop", meta: "118 BPM · F minor", color: LUMA.cyan },
  { name: "Night Drive Kit", type: "Drum kit", meta: "24 one-shots · Electronic", color: LUMA.violet },
  { name: "Soft Focus", type: "Texture", meta: "94 BPM · C major", color: LUMA.amber },
];

export default function LibraryScreen() { const router = useRouter(); return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView style={styles.scroll} contentContainerStyle={styles.content}><View><Eyebrow>LIBRARY</Eyebrow><Text style={styles.title}>Find the next layer.</Text><Text style={styles.subtitle}>Preview loops and sounds, then bring them into your studio.</Text></View><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><Text style={styles.searchText}>Search loops, kits, textures</Text></View><View style={styles.chips}><Chip active>For you</Chip><Chip>Drums</Chip><Chip>Loops</Chip><Chip>Textures</Chip></View><SectionTitle eyebrow="CURATED FOR YOU" title="Fresh sounds" detail="12 results" />{sounds.map((sound) => <Pressable key={sound.name} onPress={() => router.push("/studio")}><Card style={styles.sound}><View style={[styles.soundMark, { backgroundColor: sound.color }]}><Text style={styles.play}>▶</Text></View><View style={styles.soundBody}><Text style={styles.soundName}>{sound.name}</Text><Text style={styles.soundType}>{sound.type}</Text><Text style={styles.soundMeta}>{sound.meta}</Text></View><Text style={styles.add}>＋</Text></Card></Pressable>)}<Card style={styles.import}><Eyebrow>YOUR SOUNDS</Eyebrow><Text style={styles.importTitle}>Import from your device</Text><Text style={styles.importText}>Bring in a sample and keep it alongside your Luma Audio library.</Text></Card></ScrollView></ScreenContainer>; }

const styles = StyleSheet.create({ scroll: { flex: 1, backgroundColor: LUMA.canvas }, content: { padding: 18, paddingBottom: 42, gap: 14 }, title: { color: LUMA.text, fontSize: 29, fontWeight: "900", marginTop: 7, letterSpacing: -0.8 }, subtitle: { color: LUMA.muted, fontSize: 12, lineHeight: 17, marginTop: 5 }, search: { flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 12, padding: 13, marginTop: 8 }, searchIcon: { color: LUMA.cyan, fontSize: 20 }, searchText: { color: LUMA.muted, fontSize: 11 }, chips: { flexDirection: "row", gap: 8 }, sound: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 12 }, soundMark: { width: 46, height: 46, borderRadius: 13, alignItems: "center", justifyContent: "center" }, play: { color: LUMA.canvas, fontSize: 13 }, soundBody: { flex: 1 }, soundName: { color: LUMA.text, fontSize: 13, fontWeight: "900" }, soundType: { color: LUMA.muted, fontSize: 10, marginTop: 4 }, soundMeta: { color: "#5F6E8A", fontSize: 9, marginTop: 4 }, add: { color: LUMA.cyan, fontSize: 22 }, import: { marginTop: 3 }, importTitle: { color: LUMA.text, fontSize: 16, fontWeight: "900", marginTop: 6 }, importText: { color: LUMA.muted, fontSize: 10, lineHeight: 15, marginTop: 5 },
});
