import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, Chip, Eyebrow, LUMA } from "@/components/luma-primitives";

const sounds = [
  { name: "Deep House Drum Loop", type: "Drums", meta: "124 BPM · 4 Bars", color: LUMA.cyan },
  { name: "Analog Bassline", type: "Bass", meta: "120 BPM · C min", color: LUMA.violet },
  { name: "Dream Pad Chords", type: "Melody", meta: "100 BPM · A min", color: LUMA.amber },
  { name: "Vocal Echo", type: "Vocal", meta: "128 BPM · G maj", color: LUMA.green },
  { name: "Riser Impact", type: "FX", meta: "90 BPM · One shot", color: "#5A8DEE" },
  { name: "Vinyl Noise Sweep", type: "Texture", meta: "92 BPM · 2 Bars", color: "#EF6C9B" },
];

export default function LibraryScreen() { const router = useRouter(); return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView contentContainerStyle={styles.content}><View style={styles.topbar}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.topTitle}>Loops</Text><Text style={styles.searchIcon}>⌕</Text></View><View style={styles.heading}><Eyebrow>LOOPS & SAMPLES</Eyebrow><Text style={styles.title}>Find the next layer.</Text><Text style={styles.subtitle}>Preview a sound, then add it directly to Midnight Bloom.</Text></View><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><Text style={styles.searchText}>Search sounds and kits</Text></View><View style={styles.filters}><Chip active>All</Chip><Chip>Drums</Chip><Chip>Bass</Chip><Chip>Melody</Chip><Chip>FX</Chip></View><View style={styles.controls}><Chip>Key⌄</Chip><Chip>BPM⌄</Chip><Chip>Type⌄</Chip><Chip>☆ Favorites</Chip></View><View style={styles.list}>{sounds.map((sound) => <Card key={sound.name} style={styles.sound}><View style={[styles.soundMark, { backgroundColor: sound.color }]}><Text style={styles.play}>▶</Text></View><View style={styles.soundBody}><Text style={styles.soundName}>{sound.name}</Text><Text style={styles.soundMeta}>{sound.meta} · {sound.type}</Text><View style={styles.miniWave}>{Array.from({ length: 18 }, (_, index) => <View key={index} style={[styles.waveBar, { height: `${25 + ((index * 19) % 65)}%`, backgroundColor: sound.color }]} />)}</View></View><Pressable onPress={() => router.push("/studio")} style={styles.add}><Text style={styles.addText}>＋</Text></Pressable></Card>)}</View></ScrollView></ScreenContainer>; }

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 42, gap: 14 }, topbar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", height: 42 }, back: { color: LUMA.text, fontSize: 28 }, topTitle: { color: LUMA.text, fontSize: 12, fontWeight: "900" }, searchIcon: { color: LUMA.text, fontSize: 22 }, heading: { marginTop: 7 }, title: { color: LUMA.text, fontSize: 29, fontWeight: "900", marginTop: 7, letterSpacing: -0.8 }, subtitle: { color: LUMA.muted, fontSize: 12, lineHeight: 17, marginTop: 5 }, search: { flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: LUMA.surface, borderWidth: 1, borderColor: LUMA.border, borderRadius: 12, padding: 13, marginTop: 5 }, searchText: { color: LUMA.muted, fontSize: 11 }, filters: { flexDirection: "row", gap: 7 }, controls: { flexDirection: "row", gap: 7 }, list: { gap: 9 }, sound: { flexDirection: "row", alignItems: "center", gap: 10, padding: 10, borderRadius: 14 }, soundMark: { width: 42, height: 42, borderRadius: 11, alignItems: "center", justifyContent: "center" }, play: { color: LUMA.canvas, fontSize: 12 }, soundBody: { flex: 1 }, soundName: { color: LUMA.text, fontSize: 11, fontWeight: "900" }, soundMeta: { color: LUMA.muted, fontSize: 8, marginTop: 4 }, miniWave: { height: 19, flexDirection: "row", gap: 2, alignItems: "center", marginTop: 7 }, waveBar: { flex: 1, minWidth: 2, maxWidth: 5, borderRadius: 2 }, add: { width: 31, height: 31, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: LUMA.raised }, addText: { color: LUMA.cyan, fontSize: 19 },
});
