import { ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Card, Eyebrow, LUMA } from "@/components/luma-primitives";

export default function SettingsScreen() { return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView contentContainerStyle={styles.content}><View style={styles.topbar}><Text style={styles.title}>Settings</Text><Text style={styles.close}>×</Text></View><View style={styles.tabs}><Text style={styles.tab}>General</Text><Text style={[styles.tab, styles.activeTab]}>Audio</Text><Text style={styles.tab}>MIDI</Text><Text style={styles.tab}>Account</Text></View><Card><Eyebrow>AUDIO SETUP</Eyebrow><SettingRow title="Audio Device" detail="Core Audio" value="Core Audio⌄" /><SettingRow title="Sample Rate" detail="Project sample rate" value="48.0 kHz⌄" /><SettingRow title="Buffer Size" detail="256 samples (5.3 ms)" value="256⌄" /><SettingRow title="Input Monitoring" detail="Hear the selected input while recording" toggle /><SettingRow title="Auto Record Arm" detail="Arm the selected track on open" toggle /></Card><Card><Eyebrow>RECORDING</Eyebrow><SettingRow title="Input" detail="Default recording source" value="Built-in Mic⌄" /><SettingRow title="Metronome" detail="Count in and playback click" toggle /><SettingRow title="Metronome Level" detail="Playback volume" value="−18 dB" /><View style={styles.slider}><View style={styles.sliderFill} /><View style={styles.sliderThumb} /></View></Card><View style={styles.advanced}><Text style={styles.advancedTitle}>Advanced</Text><Text style={styles.arrow}>›</Text></View><View style={styles.brand}><Text style={styles.brandText}>LUMA AUDIO</Text><Text style={styles.brandSub}>Mobile Music Production Studio</Text></View></ScrollView></ScreenContainer>; }

function SettingRow({ title, detail, value, toggle }: { title: string; detail: string; value?: string; toggle?: boolean }) { return <View style={styles.row}><View style={styles.rowBody}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowDetail}>{detail}</Text></View>{toggle ? <Switch value={false} trackColor={{ false: LUMA.raised, true: LUMA.violet }} thumbColor={LUMA.text} /> : <Text style={styles.value}>{value}</Text>}</View>; }

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 42, gap: 14 }, topbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { color: LUMA.text, fontSize: 29, fontWeight: "900" }, close: { color: LUMA.text, fontSize: 25 }, tabs: { flexDirection: "row", gap: 6, padding: 4, borderRadius: 10, backgroundColor: LUMA.surface }, tab: { flex: 1, color: LUMA.muted, fontSize: 9, fontWeight: "900", textAlign: "center", paddingVertical: 9, borderRadius: 7 }, activeTab: { color: LUMA.text, backgroundColor: LUMA.violet }, row: { flexDirection: "row", alignItems: "center", paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: LUMA.border }, rowBody: { flex: 1 }, rowTitle: { color: LUMA.text, fontSize: 11, fontWeight: "900" }, rowDetail: { color: LUMA.muted, fontSize: 9, marginTop: 4 }, value: { color: LUMA.text, fontSize: 9, fontWeight: "900" }, slider: { height: 5, borderRadius: 3, backgroundColor: LUMA.raised, marginTop: 13, position: "relative" }, sliderFill: { position: "absolute", left: 0, top: 0, bottom: 0, width: "72%", borderRadius: 3, backgroundColor: LUMA.violet }, sliderThumb: { position: "absolute", left: "70%", top: -5, width: 15, height: 15, borderRadius: 8, backgroundColor: LUMA.text }, advanced: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16, borderWidth: 1, borderColor: LUMA.border, borderRadius: 13, backgroundColor: LUMA.surface }, advancedTitle: { color: LUMA.text, fontSize: 12, fontWeight: "900" }, arrow: { color: LUMA.muted, fontSize: 24 }, brand: { alignItems: "center", marginTop: 15 }, brandText: { color: LUMA.cyan, fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, brandSub: { color: LUMA.muted, fontSize: 9, marginTop: 5 },
});
