import { ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Card, Eyebrow, LUMA, SectionTitle } from "@/components/luma-primitives";

export default function SettingsScreen() { return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#050816]" safeAreaClassName="bg-[#050816]"><ScrollView style={styles.scroll} contentContainerStyle={styles.content}><Eyebrow>SETTINGS</Eyebrow><Text style={styles.title}>Make the studio yours.</Text><Text style={styles.subtitle}>Audio behavior and project preferences live here.</Text><SectionTitle eyebrow="AUDIO SETUP" title="Recording environment" /><Card><SettingRow title="Microphone" detail="Built-in microphone" value="Built-in" /><SettingRow title="Input monitoring" detail="Hear yourself while recording" toggle /><SettingRow title="Low-latency mode" detail="Prioritize responsiveness" toggle /></Card><SectionTitle eyebrow="PROJECTS" title="Storage & workflow" /><Card><SettingRow title="Save projects locally" detail="Keep sessions on this device" toggle /><SettingRow title="Default project format" detail="WAV · 24-bit" value="WAV" /><SettingRow title="Default BPM" detail="Starting tempo for new ideas" value="118" /></Card><Card style={styles.about}><Eyebrow>LUMA AUDIO</Eyebrow><Text style={styles.aboutTitle}>A studio that grows with you.</Text><Text style={styles.aboutText}>The current frontend is built from the approved product mockups. Audio capabilities are introduced only when they are real and testable.</Text></Card></ScrollView></ScreenContainer>; }

function SettingRow({ title, detail, value, toggle }: { title: string; detail: string; value?: string; toggle?: boolean }) { return <View style={styles.row}><View style={styles.rowBody}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowDetail}>{detail}</Text></View>{toggle ? <Switch value={false} trackColor={{ false: LUMA.raised, true: LUMA.violet }} thumbColor={LUMA.text} /> : <Text style={styles.value}>{value}</Text>}</View>; }

const styles = StyleSheet.create({ scroll: { flex: 1, backgroundColor: LUMA.canvas }, content: { padding: 18, paddingBottom: 42, gap: 14 }, title: { color: LUMA.text, fontSize: 29, fontWeight: "900", marginTop: 7, letterSpacing: -0.8 }, subtitle: { color: LUMA.muted, fontSize: 12, lineHeight: 17, marginTop: 5 }, row: { flexDirection: "row", alignItems: "center", paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: LUMA.border }, rowBody: { flex: 1 }, rowTitle: { color: LUMA.text, fontSize: 12, fontWeight: "900" }, rowDetail: { color: LUMA.muted, fontSize: 10, marginTop: 4 }, value: { color: LUMA.cyan, fontSize: 10, fontWeight: "900" }, about: { marginTop: 3 }, aboutTitle: { color: LUMA.text, fontSize: 16, fontWeight: "900", marginTop: 6 }, aboutText: { color: LUMA.muted, fontSize: 10, lineHeight: 15, marginTop: 5 },
});
