from pathlib import Path
path = Path('/home/ubuntu/luma-audio/app/(tabs)/index.tsx')
s = path.read_text()
repls = {
"type Clip = { id: string; left: number; width: number };": "type Clip = { id: string; left: number; width: number; fadeIn?: boolean; fadeOut?: boolean };",
'  const [selectedClip, setSelectedClip] = useState<{ trackId: string; clipId: string } | null>(null);': '  const [selectedClip, setSelectedClip] = useState<{ trackId: string; clipId: string } | null>(null);\n  const [beatSteps, setBeatSteps] = useState<boolean[]>([true, false, false, true, true, false, true, false, true, false, false, true, true, false, true, false]);\n  const [isSequencing, setIsSequencing] = useState(false);\n  const [masterEffects, setMasterEffects] = useState({ eq: true, compression: false, reverb: true, delay: false, limiter: true });',
'''  const duplicateSelectedClip = () => {''': '''  const trimSelectedClip = () => {
    if (!selectedClip) return;
    setTracks((current) => current.map((track) => track.id === selectedClip.trackId ? { ...track, clips: track.clips.map((clip) => clip.id === selectedClip.clipId ? { ...clip, left: clip.left + 2, width: Math.max(3, clip.width - 3) } : clip) } : track));
  };

  const splitSelectedClip = () => {
    if (!selectedClip) return;
    setTracks((current) => current.map((track) => {
      if (track.id !== selectedClip.trackId) return track;
      const clip = track.clips.find((item) => item.id === selectedClip.clipId);
      if (!clip) return track;
      const half = Math.max(2, clip.width / 2 - 1);
      return { ...track, clips: track.clips.flatMap((item) => item.id === clip.id ? [{ ...item, width: half }, { ...item, id: `${item.id}-split`, left: item.left + half + 1, width: half }] : [item]) };
    }));
  };

  const toggleFadeSelectedClip = (side: "fadeIn" | "fadeOut") => {
    if (!selectedClip) return;
    setTracks((current) => current.map((track) => track.id === selectedClip.trackId ? { ...track, clips: track.clips.map((clip) => clip.id === selectedClip.clipId ? { ...clip, [side]: !clip[side] } : clip) } : track));
  };

  const duplicateSelectedClip = () => {''',
'{selectedClip && <View style={styles.clipActions}><Text style={styles.clipActionLabel}>CLIP SELECTED</Text><Pressable onPress={duplicateSelectedClip}><Text style={styles.clipActionText}>Duplicate</Text></Pressable><Pressable onPress={deleteSelectedClip}><Text style={[styles.clipActionText, { color: COLORS.red }]}>Delete</Text></Pressable></View>}': '{selectedClip && <View style={styles.clipActions}><Text style={styles.clipActionLabel}>CLIP SELECTED</Text><Pressable onPress={trimSelectedClip}><Text style={styles.clipActionText}>Trim</Text></Pressable><Pressable onPress={splitSelectedClip}><Text style={styles.clipActionText}>Split</Text></Pressable><Pressable onPress={() => toggleFadeSelectedClip("fadeIn")}><Text style={styles.clipActionText}>Fade in</Text></Pressable><Pressable onPress={duplicateSelectedClip}><Text style={styles.clipActionText}>Duplicate</Text></Pressable><Pressable onPress={deleteSelectedClip}><Text style={[styles.clipActionText, { color: COLORS.red }]}>Delete</Text></Pressable></View>}',
'{activeTool === "Beat" && <BeatPanel onAction={handleToolAction} />}': '{activeTool === "Beat" && <BeatPanel onAction={handleToolAction} steps={beatSteps} onToggleStep={(index) => setBeatSteps((current) => current.map((value, step) => step === index ? !value : value))} isSequencing={isSequencing} onSequence={() => setIsSequencing((value) => !value)} />}',
'{activeTool === "Mix" && <MixPanel />}': '{activeTool === "Mix" && <MixPanel effects={masterEffects} onToggle={(effect) => setMasterEffects((current) => ({ ...current, [effect]: !current[effect] }))} />}',
'''function BeatPanel({ onAction }: { onAction: (action: string) => void }) {
  return <View><View style={styles.padGrid}>{["KICK", "SNARE", "HAT", "CLAP", "808", "RIM", "OPEN", "FX"].map((pad, index) => <Pressable key={pad} onPress={() => onAction(index === 0 ? "Add pattern" : "Pad tapped")} style={[styles.pad, index === 0 && styles.padAccent]}><Text style={styles.padLabel}>{pad}</Text><Text style={styles.padNumber}>0{index + 1}</Text></Pressable>)}</View><View style={styles.patternRow}><Text style={styles.label}>PATTERN 01 · 2 BARS</Text><Text style={styles.label}>SWING 54%</Text></View><View style={styles.stepGrid}>{Array.from({ length: 16 }).map((_, index) => <View key={index} style={[styles.step, [0, 3, 4, 8, 10, 12].includes(index) && styles.stepOn]} />)}</View><Pressable style={styles.secondaryAction} onPress={() => onAction("Add pattern")}><Text style={styles.secondaryActionText}>Add pattern to timeline</Text><Text style={styles.secondaryActionIcon}>＋</Text></Pressable></View>;
}''': '''function BeatPanel({ onAction, steps, onToggleStep, isSequencing, onSequence }: { onAction: (action: string) => void; steps: boolean[]; onToggleStep: (index: number) => void; isSequencing: boolean; onSequence: () => void }) {
  return <View><View style={styles.padGrid}>{["KICK", "SNARE", "HAT", "CLAP", "808", "RIM", "OPEN", "FX"].map((pad, index) => <Pressable key={pad} onPress={() => onAction(index === 0 ? "Add pattern" : "Pad tapped")} style={[styles.pad, index === 0 && styles.padAccent]}><Text style={styles.padLabel}>{pad}</Text><Text style={styles.padNumber}>0{index + 1}</Text></Pressable>)}</View><View style={styles.patternRow}><Text style={styles.label}>PATTERN 01 · 2 BARS</Text><Text style={styles.label}>SWING 54%</Text></View><View style={styles.stepGrid}>{steps.map((on, index) => <Pressable key={index} onPress={() => onToggleStep(index)} style={[styles.step, on && styles.stepOn]} />)}</View><View style={styles.sequenceRow}><Pressable onPress={onSequence} style={[styles.sequenceButton, isSequencing && styles.sequenceButtonActive]}><Text style={styles.sequenceText}>{isSequencing ? "Stop sequencer" : "Play pattern"}</Text></Pressable><Text style={styles.sequenceMeta}>16 STEPS · VELOCITY EDITABLE</Text></View><Pressable style={styles.secondaryAction} onPress={() => onAction("Add pattern")}><Text style={styles.secondaryActionText}>Add pattern to timeline</Text><Text style={styles.secondaryActionIcon}>＋</Text></Pressable></View>;
}''',
'''function MixPanel() {
  return <View><View style={styles.mixStrip}>{["VOCAL", "DRUMS", "BASS", "MASTER"].map((name, index) => <View key={name} style={styles.mixChannel}><View style={styles.mixMeter}><View style={[styles.mixMeterFill, { height: `${36 + index * 12}%`, backgroundColor: index === 3 ? COLORS.cyan : COLORS.violet }]} /></View><View style={styles.fader}><View style={[styles.faderKnob, { bottom: `${38 + index * 7}%` }]} /></View><Text style={styles.mixName}>{name}</Text></View>)}</View><View style={styles.mixFooter}><Text style={styles.label}>MASTER PEAK −3.2 dB</Text><Text style={styles.mixDetail}>Open advanced mix</Text></View></View>;
}''': '''function MixPanel({ effects, onToggle }: { effects: Record<string, boolean>; onToggle: (effect: keyof typeof effects) => void }) {
  return <View><View style={styles.mixStrip}>{["VOCAL", "DRUMS", "BASS", "MASTER"].map((name, index) => <View key={name} style={styles.mixChannel}><View style={styles.mixMeter}><View style={[styles.mixMeterFill, { height: `${36 + index * 12}%`, backgroundColor: index === 3 ? COLORS.cyan : COLORS.violet }]} /></View><View style={styles.fader}><View style={[styles.faderKnob, { bottom: `${38 + index * 7}%` }]} /></View><Text style={styles.mixName}>{name}</Text></View>)}</View><View style={styles.effectGrid}>{Object.keys(effects).map((effect) => <Pressable key={effect} onPress={() => onToggle(effect)} style={[styles.effectChip, effects[effect] && styles.effectChipActive]}><Text style={[styles.effectText, effects[effect] && styles.effectTextActive]}>{effect.toUpperCase()}</Text></Pressable>)}</View><View style={styles.mixFooter}><Text style={styles.label}>MASTER PEAK −3.2 dB</Text><Text style={styles.mixDetail}>EXPORT / STEMS</Text></View></View>;
}''',
'  const [isSequencing, setIsSequencing] = useState(false);': '  const [isSequencing, setIsSequencing] = useState(false);\n  const [exportQuality, setExportQuality] = useState("WAV 24-BIT");',
'<Pressable style={styles.menuButton} onPress={() => Alert.alert("Project settings", "Project details and export controls will live here.")}>': '<Pressable style={styles.menuButton} onPress={() => Alert.alert("Export project", "Choose a format for the final mix or individual stems.", [{ text: "WAV 24-bit", onPress: () => setExportQuality("WAV 24-BIT") }, { text: "MP3 320 kbps", onPress: () => setExportQuality("MP3 320 KBPS") }, { text: "Cancel", style: "cancel" }])}>',
'  stepOn: { backgroundColor: COLORS.cyan, borderColor: COLORS.cyan },': '  stepOn: { backgroundColor: COLORS.cyan, borderColor: COLORS.cyan },\n  sequenceRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 14 },\n  sequenceButton: { borderRadius: 10, backgroundColor: COLORS.surfaceRaised, borderWidth: 1, borderColor: COLORS.border, paddingHorizontal: 12, paddingVertical: 9 },\n  sequenceButtonActive: { backgroundColor: "#20103B", borderColor: COLORS.violet },\n  sequenceText: { color: COLORS.text, fontSize: 10, fontWeight: "800" },\n  sequenceMeta: { color: COLORS.muted, fontSize: 8, fontWeight: "700" },',
'  mixFooter: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: COLORS.border, marginTop: 14, paddingTop: 13 },': '  effectGrid: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: COLORS.border },\n  effectChip: { borderRadius: 9, borderWidth: 1, borderColor: COLORS.border, paddingHorizontal: 9, paddingVertical: 7 },\n  effectChipActive: { backgroundColor: "#20103B", borderColor: COLORS.violet },\n  effectText: { color: COLORS.muted, fontSize: 9, fontWeight: "800" },\n  effectTextActive: { color: COLORS.violet },\n  mixFooter: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: COLORS.border, marginTop: 14, paddingTop: 13 },'
}
for old, new in repls.items():
    if old not in s: print('MISSING', old[:90].replace('\n',' / '))
    s = s.replace(old, new, 1)
path.write_text(s)
